# -*- coding: utf-8 -*-
"""
Created on Mon Aug 19 11:57:17 2019

@author: Alina Arseniev
"""

gender_train={'pos': ['her', 'hers', 'herself', 'she', 
                      'womanly', 'woman', 'women', 'girl', 'girls', 
            	'lady', 'gal', 'gals', 'madame', 'ladies', 'lady',
          	'mother', 'mothers', 'mom', 'moms', 'mommy', 'mama',  'granddaughter', 'daughter', 'daughters', 'aunt', 'godmother', 
          	'grandma', 'grandmothers', 'grandmother', 'sister', 'sisters', 'aunts', 'stepmother', 'granddaughters', 'niece',
          	'fiancee', 'ex_girlfriend', 'girlfriends', 'wife', 'wives', 'girlfriend',  'widow',
           	'twin_sister', 'younger_sister', 'teenage_girl', 'teenage_girls', 'eldest_daughter',
            'queen', 'queens', 'princess', 
           	'maternal', 'maternity', 'motherhood', 'sisterhood', 'girlhood',  'sorority', 
         	'older_sister', 'oldest_daughter', 'stepdaughter'],
             'neg': ['him', 'his', 'himself', 'he', 'manly',  'man', 'men', 'boy', 'boys', 'guy', 'dude',
           	 'dudes', 'sir', 'guys', 'gentleman','father', 'fathers', 'dad', 'dads', 'daddy', 'papa',  'grandson' , 'son', 'sons', 'uncle', 'godfather', 
           	'grandpa', 'grandfathers', 'grandfather', 'brother', 'brothers' , 'uncles', 'stepfather', 'grandsons', 'nephew',
           	'fiance', 'ex_boyfriend', 'boyfriends', 'husband', 'husbands', 'boyfriend',  'widower',
           	 'twin_brother', 'younger_brother', 'teenage_boy', 'teenage_boys', 'eldest_son', 
            	'king', 'kings', 'prince', 
          	 'paternal', 'paternity', 'fatherhood', 'brotherhood', 'boyhood',  'fraternity', 'older_brother', 'oldest_son', 'stepson']}

health_train={'pos': ['fertile', 'help_prevent', 'considered_safe', 'safer', 'healthy', 'healthy', 'healthy', 'healthy', 'healthy',
            'healthful', 'well_balanced', 'natural', 'healthy', 'athletic','physically_active', 'health',
            'health', 'nutritious','nourishing', 'stronger', 'strong','wellness', 'safe', 'nutritious_food','exercise',
            'physically_fit', 'unprocessed', 'healthier_foods', 'nutritious_foods', 'nutritious', 'nutritious',
           'healthy_eating', 'healthy_diet', 'healthy_diet', 'nourishing', 'nourished', 'regular_exercise', 'safety', 'safe', 
            'helpful', 'beneficial', 'healthy', 'healthy', 'sturdy', 'lower_risk', 'reduced_risk', 'decreased_risk', 'nutritious_foods', 'whole_grains', 'healthier_foods',
            'healthier_foods', 'physically_active', 'physical_activity', 'nourished', 'vitality', 'energetic', 'able_bodied',
            'resilience', 'strength', 'less_prone', 'sanitary', 'clean',  'healing', 'heal', 'salubrious']   , 'neg': ['infertile', 'cause_harm','potentially_harmful','riskier', 'unhealthy', 'sick', 'ill', 'frail', 'sickly', 
            'unhealthful','unbalanced', 'unnatural', 'dangerous', 'sedentary', 'inactive', 'illness', 
            'sickness', 'toxic', 'unhealthy', 'weaker', 'weak', 'illness', 'unsafe', 'unhealthy_foods', 'sedentary',
            'inactive', 'highly_processed', 'processed_foods', 'junk_foods', 'unhealthy_foods', 'junk_foods',
               'processed_foods', 'processed_foods', 'fast_food', 'unhealthy_foods', 'deficient', 'sedentary', 'hazard','hazardous', 
            'harmful', 'injurious',  'chronically_ill', 'seriously_ill', 'frail', 'higher_risk', 'greater_risk', 'increased_risk', 'fried_foods', 'fried_foods',
            'fatty_foods', 'sugary_foods', 'sedentary', 'physical_inactivity', 'malnourished', 'lethargy', 'lethargic', 'disabled',
            'susceptibility', 'weakness', 'more_susceptible', 'filthy', 'dirty', 'harming', 'hurt', 'deleterious'] }

ses_train={'pos': ['wealth', 'wealthier', 'wealthiest', 'affluence', 'prosperity', 'wealthy', 'affluent', 'affluent', 'prosperous',
                'prosperous','prosperous','disposable_income',  'wealthy','suburban','luxurious','upscale','upscale', 'luxury', 
                'richest', 'privileged', 'moneyed', 'privileged', 'privileged', 'educated', 'employed', 
                'elite', 'upper_income', 'upper_class', 'employment', 'riches', 'millionaire', 'aristocrat', 'college_educated',
                'abundant', 'abundance', 'luxury', 'profitable', 'profit', 'well_educated', 'elites', 'heir', 'well_heeled', 
                'white_collar', 'higher_incomes', 'bourgeois', 'fortunate', 'successful','economic_growth', 'prosper', 'suburbanites'], 'neg': ['poverty', 'poorer', 'poorest', 'poverty', 'poverty', 'impoverished', 'impoverished',  'needy',  'impoverished',
                 'poor', 'needy', 'broke', 'needy', 'slum', 'ghetto', 'slums', 'ghettos', 'poor_neighborhoods', 
                'poorest', 'underserved', 'disadvantaged','marginalized', 'underprivileged', 'uneducated', 'unemployed', 
                'marginalized', 'low_income', 'underclass','unemployment', 'rags', 'homeless', 'peasant', 'college_dropout', 
                'lacking', 'lack', 'squalor', 'bankrupt', 'debt', 'illiterate' ,'underclass', 'orphan',  'destitute', 
                'blue_collar', 'low_income', 'neediest', 'less_fortunate', 'unsuccessful', 'economic_crisis', 'low_wage', 'homeless'] }

gender_test= {'pos': ['goddess', 'single_mother', 'girlish', 'feminine', 'young_woman', 'little_girl', 'ladylike', 'my_mother', 
           'teenage_daughter', 'mistress', 'great_grandmother', 'adopted_daughter', 'femininity', 'motherly', 'matronly', 
           'showgirl', 'housewife', 'vice_chairwoman', 'co_chairwoman', 'spokeswoman', 'governess', 'divorcee', 'spinster', 
           'maid', 'countess', 'pregnant_woman', 'landlady', 'seamstress', 'young_girl', 'waif', 'femme_fatale','comedienne'],
 'neg': ['boyish', 'masculine',  'lad', 'policeman', 'macho', 'gentlemanly', 'machismo',  'teenage_son', 
            'beau', 'great_grandfather', 'tough_guy', 'masculinity', 'mr', 'bad_boy', 'spokesman', 'baron', 'adult_male', 'landlord', 'vice_chairman', 
           'co_chairman','young_man', 'fireman', 'bearded','busboy', 'mustachioed', 'homeless_man', 'gent', 'strongman'] }


health_test={'pos':  ['balanced_diet', 'healthfulness', 'active',  'jogging', 'stopping_smoking', 'vigor', 
          'flourishing', 'sustaining', 'hygienic', 'hearty', 'enduring', 'energized', 'wholesome', 
           'holistic', 'healed', 'fitter', 'health_conscious', 'more_nutritious', 'live_longer',  'exercising_regularly',
           'healthier_choices', 'healthy_habits', 'healthy_lifestyle', 'healthful_eating', 'immune', 'virile', 'vigorous'] , 'neg': ['deadly', 'diseased',  'adverse', 'risky', 'fatal', 'filthy', 'epidemic', 'crippling', 'carcinogenic', 'carcinogen',
           'crippled', 'afflicted', 'contaminated', 'fatigued', 'detrimental', 'bedridden', 'incurable', 'hospitalized',
           'infected', 'ailing', 'debilitated', 'poisons', 'disabling', 'life_threatening', 'debilitating', 
           'chronic_illness', 'disease', 'stroke','illnesses', 'ailment',
            'plague', 'poisonous', 'smoking'] }

ses_test={'pos': ['rich', 'billionaire', 'banker',  'fortune', 'heiress', 'cosmopolitan', 'ornate', 'entrepreneur', 'sophisticated',
                'aristocratic', 'investor', 'highly_educated', 'better_educated',  'splendor', 
               'businessman', 'opulent', 'multimillionaire', 'philanthropist', 'estate', 'estates', 'chateau', 'fortunes', 
               'financier', 'young_professionals','tycoon', 'baron', 'grandeur', 'magnate', 
               'investment_banker', 'venture_capitalist', 'upwardly_mobile', 'highly_skilled', 'yuppies', 'genteel'], 'neg': ['homelessness', 'ruin', 'ruined', 'downtrodden', 'less_affluent',
                'housing_project', 'homeless_shelters', 'indigent', 'jobless', 'welfare',  
                'temporary_shelters','housing_projects', 'subsidized_housing', 'starving', 'beggars', 'orphanages',
                'dispossessed', 'uninsured', 'welfare_recipients', 'food_stamps', 
                'malnutrition',  'underemployed', 'disenfranchised', 'servants', 'displaced', 'poor_families']  }

#These are in the vocabulary of our NYT model at least 50 times
purity= {'pos': ['piety','pious','purity','pure','purely','clean','cleanly','cleaner','cleaning','sterility','sterilize','sterilized',
'sacred','chastity', 'chaste', 'holy', 'saint','saintly','wholesome','celibacy', 'celibate','virgin', 'virgins', 'virginity', 'virginal', 'austerity','integrity',
 'modestly', 'abstinence','upright', 'limpid','unadulterated', 'maiden' ,'virtuous', 'refined','decent','decency','immaculate','innocent','pristine','church', 'preserve'],
'neg': ['disgust', 'disgusting', 'disgusted', 'depravity', 'depraved', 'disease','diseased', 'contagious', 'contagion', 'indecent', 'sin',
 'sinful', 'sinner', 'sinners','sins','slut','whore','dirty','dirty','profane','profanity', 'gross', 'repulsive', 'repulsed', 'sick', 'sickness',
 'promiscuous', 'promiscuity', 'lewd', 'adultery', 'debauchery','tramp', 'prostitution','prostitute','prostitutes','wanton', 'filthy', 'filth', 'trashy', 'obscenity', 'obscene', 'lax', 'tainted', 'taint', 'stained', 'stain', 'stains', 'tarnish', 'tarnished', 'debased', 'wicked', 'blemish', 'exploitation', 'exploitative', 'wretched',
'heretical', 'exploit', 'exploiting', 'exploited', 'ruin', 'ruined']}

#These are words in the Moral Foundations Theory lexicon that are also in the vocabulary of our overall NYT model least 50 times
moral_mfd= {'pos': ['guarding',
 'legally',
 'protect',
 'worthy',
 'cleaner',
 'loyal',
 'sterility',
 'obedience',
 'ranked',
 'respects',
 'compliance',
 'protected',
 'safest',
 'cadre',
 'family',
 'sterilize',
 'chaste',
 'deference',
 'virgin',
 'good',
 'virginal',
 'order',
 'equality',
 'permission',
 'legal',
 'holy',
 'nationally',
 'morality',
 'balanced',
 'egalitarian',
 'lawful',
 'pristine',
 'character',
 'ethically',
 'defends',
 'empathy',
 'compassionate',
 'justified',
 'guild',
 'father',
 'allegiance',
 'righteous',
 'motherly',
 'submitted',
 'ethics',
 'national',
 'safely',
 'respected',
 'unison',
 'proper',
 'obey',
 'caste',
 'securing',
 'morals',
 'decency',
 'permit',
 'pure',
 'serve',
 'hierarchical',
 'saint',
 'compassion',
 'devoting',
 'submissive',
 'value',
 'compliant',
 'safe',
 'guard',
 'communes',
 'security',
 'decent',
 'impartiality',
 'abstinence',
 'commendable',
 'joint',
 'defending',
 'legality',
 'principles',
 'exemplary',
 'patriotic',
 'duty',
 'comply',
 'purely',
 'guards',
 'cohort',
 'ally',
 'goodness',
 'honesty',
 'united',
 'chastity',
 'honest',
 'community',
 'equity',
 'peacefully',
 'familial',
 'communism',
 'care',
 'reverent',
 'correct',
 'abide',
 'submission',
 'peace',
 'fellowship',
 'canon',
 'respect',
 'patriot',
 'status',
 'rights',
 'refined',
 'fellow',
 'leader',
 'upstanding',
 'sacred',
 'shield',
 'defense',
 'celibacy',
 'class',
 'obedient',
 'submit',
 'nation',
 'mothers',
 'safety',
 'balance',
 'ranking',
 'clean',
 'law',
 'blameless',
 'values',
 'fellows',
 'protects',
 'principle',
 'idealistic',
 'loyalty',
 'defend',
 'caring',
 'dutiful',
 'communal',
 'moral',
 'submits',
 'limpid',
 'defended',
 'control',
 'virginity',
 'supremacy',
 'fair',
 'together',
 'collective',
 'unadulterated',
 'impartial',
 'insider',
 'principled',
 'maiden',
 'doctrine',
 'tolerant',
 'comrade',
 'preserve',
 'reasonable',
 'solidarity',
 'laudable',
 'ordered',
 'worth',
 'innocent',
 'cliques',
 'secure',
 'wholesome',
 'authority',
 'justification',
 'dutifully',
 'ideal',
 'member',
 'austerity',
 'equals',
 'immaculate',
 'morally',
 'protection',
 'communities',
 'equally',
 'obeying',
 'deferential',
 'bourgeoisie',
 'authoritative',
 'orderly',
 'leaders',
 'ethical',
 'respectfully',
 'equivalent',
 'position',
 'unbiased',
 'ranks',
 'pious',
 'sterilized',
 'integrity',
 'justice',
 'virgins',
 'saintly',
 'reciprocal',
 'mothering',
 'sympathetic',
 'traditions',
 'commune',
 'defer',
 'fairness',
 'patriotism',
 'upright',
 'homeland',
 'clique',
 'lesson',
 'devoted',
 'virtuous',
 'honestly',
 'equal',
 'noble',
 'sympathy',
 'benefits',
 'obeyed',
 'submitting',
 'unite',
 'purity',
 'piety',
 'celibate',
 'mother',
 'guarded',
 'tradition',
 'cleaning',
 'rank',
 'shelter',
 'church',
 'righteousness',
 'hierarchy',
 'benefit',
 'traditionally',
 'respectful',
 'revere',
 'cleanly',
 'modestly',
 'ideally',
 'traditional',
 'constant',
 'command',
 'devote',
 'empathetic',
 'families',
 'group',
 'secured'], 'neg':   
    ['suffered',
 'attacking',
 'tramp',
 'whore',
 'stains',
 'stained',
 'betrayed',
 'subversive',
 'offensive',
 'fight',
 'endangered',
 'immigrant',
 'suffering',
 'injustice',
 'agitated',
 'disgusting',
 'violent',
 'treachery',
 'wounded',
 'preference',
 'impair',
 'abandons',
 'killer',
 'defy',
 'wanton',
 'alienate',
 'unfairly',
 'disgusted',
 'destroy',
 'contagion',
 'damaging',
 'prostitutes',
 'bigotry',
 'tarnished',
 'unjust',
 'immigrants',
 'dishonest',
 'damaged',
 'wretched',
 'depravity',
 'lawlessness',
 'foreign',
 'betray',
 'obstruct',
 'kill',
 'discrimination',
 'damage',
 'suffer',
 'segregation',
 'deceiving',
 'bigot',
 'betrays',
 'sin',
 'attacked',
 'rebels',
 'abusive',
 'attack',
 'exclude',
 'defying',
 'wrongly',
 'refuse',
 'exploit',
 'deceive',
 'bad',
 'inequality',
 'tarnish',
 'enemy',
 'segregated',
 'offends',
 'hurt',
 'disrespectful',
 'warring',
 'detrimental',
 'individualistic',
 'abuse',
 'renegade',
 'riots',
 'protest',
 'illegal',
 'fighting',
 'promiscuity',
 'terrorists',
 'stain',
 'prejudiced',
 'immigration',
 'defiance',
 'unfaithful',
 'disease',
 'unjustly',
 'evil',
 'immoral',
 'harm',
 'heretical',
 'defiant',
 'spurn',
 'killing',
 'suffers',
 'defector',
 'indecent',
 'killers',
 'lewd',
 'filth',
 'excludes',
 'slut',
 'profane',
 'subversion',
 'filthy',
 'offended',
 'endanger',
 'brutality',
 'ruin',
 'abandoning',
 'hurting',
 'ruins',
 'oppose',
 'rebellion',
 'sinful',
 'insurgent',
 'obscenity',
 'riot',
 'excluded',
 'crushing',
 'jilted',
 'denounce',
 'wronged',
 'detriment',
 'abandon',
 'taint',
 'wicked',
 'exploitation',
 'crushed',
 'unscrupulous',
 'sinner',
 'sinners',
 'diseased',
 'disproportionate',
 'discriminating',
 'offend',
 'crush',
 'harming',
 'depraved',
 'repulsed',
 'wounds',
 'wounding',
 'rebel',
 'dissenting',
 'tainted',
 'repulsive',
 'exploitative',
 'foreigner',
 'dissident',
 'adultery',
 'war',
 'cruel',
 'illegally',
 'killed',
 'harmful',
 'dishonesty',
 'crushes',
 'terrorist',
 'exploited',
 'wars',
 'gross',
 'trashy',
 'blemish',
 'prostitute',
 'dirty',
 'lax',
 'lawless',
 'treacherous',
 'hurts',
 'disproportionately',
 'rebellious',
 'violence',
 'exclusion',
 'exploits',
 'betrayal',
 'kills',
 'unfairness',
 'agitation',
 'promiscuous',
 'enemies',
 'betraying',
 'offending',
 'individual',
 'brutal',
 'foreigners',
 'individualism',
 'prejudice',
 'unfair',
 'wrong',
 'excluding',
 'bias',
 'obscene',
 'stomp',
 'sins',
 'prostitution',
 'attacks',
 'profanity',
 'debased',
 'deserted',
 'exploiting',
 'wound',
 'discriminatory',
 'fights',
 'abandoned',
 'unequal',
 'contagious',
 'sick',
 'cruelty',
 'debauchery',
 'harms',
 'treason',
 'disrespect',
 'disgust',
 'spy',
 'dissent',
 'ruined',
 'sickness',
 'favoritism',
 'harmed',
 'rioting',
 'terrorism']}


#just the gender words used by Bolukbasi et al
genderboluk_train={'pos': ['she', 'her', 'woman', 'mary', 'herself', 'daughter', 'mother', 'gal', 'girl','female'], 'neg': [ 'he', 'his', 'man', 'john' , 'himself', 'son' , 'father', 'guy', 'boy', 'male']  } #HOWEVER note that Bolukbasi runs these using capital Mary and capital John, on the GoogleNews model where some words are lowercased and others are capitalized. 


#gender2, compared to gender, adds some noisy words (words that are stereotypically gendered, but not necessarily part of their definition). This is to help prevent overfitting.
gender2_train={'pos': [ 'girl', 'girls', 'her', 'hers', 'herself', 'she', 
            'lady', 'gal', 'gals', 'madame', 'ladies', 'lady',
          'mother', 'mothers', 'mom', 'moms', 'mommy', 'mama', 'ma', 'granddaughter', 'daughter', 'daughters', 'aunt', 'godmother', 
          'grandma', 'grandmothers', 'grandmother', 'sister', 'sisters', 'aunts', 'stepmother', 'granddaughters', 'niece',
        'fiancee', 'ex_girlfriend', 'girlfriends', 'wife', 'wives', 'girlfriend', 'bride', 'brides', 'widow',
           'twin_sister', 'younger_sister', 'teenage_girl', 'teenage_girls', 'eldest_daughter','estranged_wife', 'schoolgirl',
        'businesswoman', 'congresswoman' , 'chairwoman', 'councilwoman', 'waitress', 'hostess', 'convent', 'heiress', 
           'saleswoman', 'queen', 'queens', 'princess', 'nun' , 'nuns', 'heroine', 'actress', 'actresses', 'uterus', 'vagina', 'ovarian_cancer',
        'maternal', 'maternity', 'motherhood', 'sisterhood', 'girlhood', 'matriarch', 'sorority', 'mare', 'hen', 'hens', 'filly', 'fillies',
          'deer', 'older_sister', 'oldest_daughter', 'stepdaughter', 'pink',  'cute', 'dependent', 'nurturing', 'hysterical', 'bitch',  'dance', 'dancing'], 'neg': ['boy', 'boys', 'him', 'his', 'himself', 'he', 'guy', 'dude',
            'dudes', 'sir', 'guys', 'gentleman','father', 'fathers', 'dad', 'dads', 'daddy', 'papa', 'pa', 'grandson' , 'son', 'sons', 'uncle', 'godfather', 
        'grandpa', 'grandfathers', 'grandfather', 'brother', 'brothers' , 'uncles', 'stepfather', 'grandsons', 'nephew',
           'fiance', 'ex_boyfriend', 'boyfriends', 'husband', 'husbands', 'boyfriend', 'groom', 'grooms', 'widower',
            'twin_brother', 'younger_brother', 'teenage_boy', 'teenage_boys', 'eldest_son', 'estranged_husband', 'schoolboy',
            'businessman', 'congressman', 'chairman', 'councilman', 'waiter', 'host', 'monastery', 'heir', 'salesman', 
            'king', 'kings', 'prince', 'monk', 'monks', 'hero', 'actor', 'actors', 'prostate', 'penis', 'prostate_cancer', 
        'paternal', 'paternity', 'fatherhood', 'brotherhood', 'boyhood', 'patriarch', 'fraternity', 'stallion', 'rooster', 'roosters', 'colt',
           'colts', 'bull', 'older_brother', 'oldest_son', 'stepson', 'blue' ,'manly', 'independent', 'aggressive', 'angry', 'jerk', 'wrestle', 'wrestling'  ] }
#gender3, compared to gender, includes fewer words that are explicily gendered (e.g., "she" and "he" are removed) and adds some noisy words (words that are stereotypically gendered, but not necessarily part of their definition). This is help to prevent overfitting. 
gender3_train={'pos': ['madame', 'ladies', 'lady',
          'mother', 'mothers', 'mom', 'mama', 'granddaughter', 'daughter', 'daughters', 'aunt', 'godmother', 
          'grandma', 'grandmothers', 'grandmother', 'sister', 'sisters', 'aunts', 'stepmother', 'granddaughters', 'niece',
        'fiancee', 'ex_girlfriend', 'girlfriends', 'wife', 'wives', 'girlfriend', 'bride', 'brides', 'widow',
           'twin_sister', 'younger_sister', 'teenage_girl', 'teenage_girls', 'eldest_daughter','estranged_wife', 'schoolgirl',
        'businesswoman', 'congresswoman' , 'chairwoman', 'councilwoman', 'waitress', 'hostess', 'convent', 'heiress', 
           'saleswoman', 'queen', 'queens', 'princess', 'nun' , 'nuns', 'heroine', 'actress', 'actresses', 'uterus', 'vagina', 'ovarian_cancer',
        'maternal', 'maternity', 'motherhood', 'sisterhood', 'girlhood', 'matriarch', 'sorority', 'mare', 'hen', 'hens', 'filly', 'fillies',
          'deer', 'older_sister', 'oldest_daughter', 'stepdaughter', 'pink', 'cute', 'dependent', 'nurturing', 'hysterical', 'bitch',  'dance', 'dancing'], 'neg': ['sir', 'guys', 'gentleman','father', 'fathers', 'dad', 'papa', 'grandson' , 'son', 'sons', 'uncle', 'godfather', 
        'grandpa', 'grandfathers', 'grandfather', 'brother', 'brothers' , 'uncles', 'stepfather', 'grandsons', 'nephew',
           'fiance', 'ex_boyfriend', 'boyfriends', 'husband', 'husbands', 'boyfriend', 'groom', 'grooms', 'widower',
            'twin_brother', 'younger_brother', 'teenage_boy', 'teenage_boys', 'eldest_son', 'estranged_husband', 'schoolboy',
            'businessman', 'congressman', 'chairman', 'councilman', 'waiter', 'host', 'monastery', 'heir', 'salesman', 
            'king', 'kings', 'prince', 'monk', 'monks', 'hero', 'actor', 'actors', 'prostate', 'penis', 'prostate_cancer', 
        'paternal', 'paternity', 'fatherhood', 'brotherhood', 'boyhood', 'patriarch', 'fraternity', 'stallion', 'rooster', 'roosters', 'colt',
           'colts', 'bull', 'older_brother', 'oldest_son', 'stepson', 'blue' ,'manly', 'independent', 'aggressive', 'angry', 'jerk', 'wrestle', 'wrestling'  ] }



